version: '2'
services:
    mesos-master:
        container_name: mesos-master
        image: lilidata/mesos:1.3.0
        restart: always
        environment:
            - MESOS_CLUSTER=liligo-data-platform
            - MESOS_LOG_DIR=/tmp/log
            - MESOS_GC_DELAY=2days
            - MESOS_WORK_DIR=/tmp/mesos
            - MESOS_ZK=zk://{Exhibitor nodes}/{MESOS path in zk}
            - MESOS_QUORUM={Based on the number of nodes you spawn}
        logging:
          options:
            max-size: 1G
        network_mode: "host"
        volumes:
          - /opt/docker-tmp/mesos-master:/tmp
        entrypoint: mesos-master

    mesos-agent:
        container_name: mesos-agent
        image: lilidata/mesos:1.3.0
        restart: always
        pid: "host"
        privileged: true
        environment:
            - MESOS_LOG_DIR=/tmp/log
            - MESOS_GC_DELAY=3days
            - MESOS_WORK_DIR=/tmp/mesos
            - MESOS_DOCKER=/usr/bin/docker
            - MESOS_CONTAINERIZERS=docker,mesos
            - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=3mins
            - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
            - MESOS_ZK=zk://{Exhibitor nodes}/{MESOS path in zk}
        logging:
          options:
            max-size: 1G
        network_mode: "host"
        volumes:
           - /sys:/sys:ro
           - /var/run/docker.sock:/var/run/docker.sock
           - /opt/docker-tmp/mesos-agent:/tmp
        entrypoint: mesos-slave

    exhibitor:
        container_name: exhibitor
        image: lilidata/exhibitor:1.5.6
        restart: always
        environment:
            - PORT=8082
            - CONFIG=/exhibitor/exhibitor.properties.default
            - HOSTNAME="${HOSTNAME}"
        logging:
          options:
            max-size: 1G
        network_mode: "host"
        volumes:
          - "${pwd}/configs/exhibitor.properties:/exhibitor/exhibitor.properties.default"
          - /opt/exhibitor/:/zookeeper/data
